name: Build

on:
  push:
    branches: [ public ]
  pull_request:
    branches: [ public ]

jobs:
  win64-build:

    runs-on: windows-latest
    defaults:
      run:
        shell: msys2 {0}
    steps:
    - name: setup-msys2
      uses: msys2/setup-msys2@v2
      with:
        msystem: MINGW64
        path-type: minimal
        update: true
        install: >-
          git
          autotools
          base-devel
          mingw-w64-x86_64-toolchain
          mingw-w64-x86_64-libtool
          mingw-w64-x86_64-libxml2
          mingw-w64-x86_64-zlib
    - name: checkout
      uses: actions/checkout@v2
    - name: autogen
      run: sh ./autogen.sh
    - name: configure
      run: ./configure --enable-debug
    - name: make
      run: make -j$(nproc)
    - name: make check
      run: make -j$(nproc) check
    - name: make distcheck
      run: make -j$(nproc) distcheck
    - name: upload debug artifacts
      uses: actions/upload-artifact@v2
      if: ${{ failure() }}
      with:
        name: test-logs
        path: |
          **/tests/test-suite.log
          **/tests/samples/*.log
